### ISSUE TITLE
Fix bot support role checking in non-VFL guilds

### ISSUE THREAD

**Issue by GlitchMasta47** [Voxel-Fox-Ltd/VoxelBotUtils#34]
In guilds that aren't discord.gg/vfl, any commands that require a user to be bot support do not work.

**Comment by 4Kaylum** [comment]
I believe this is pretty easy to fix presuming the bot properly sets it's guild id in the config - I can fetch support guild, fetch member from that, etc. The real issue is that it's another API call for every time someone runs the command, but I guess that's not *too* too bad; support commands shouldn't really be run that often.
