### ISSUE TITLE
`updates` silently fails if a news/updates channel isn't set

### ISSUE THREAD

**Issue by GlitchMasta47** [Voxel-Fox-Ltd/VoxelBotUtils#90]

**Comment by 4Kaylum** [comment]
If the updates channel isn't set then the command is automatically disabled (https://github.com/Voxel-Fox-Ltd/VoxelBotUtils/blob/master/voxelbotutils/cogs/simple_bot_settings.py#L56). You're able to run it still because you're an owner. If you're still experiencing this issue on an alt account, do leave another comment.
